/**
 * @file
 * @brief Wayland protocol definitions for buffer queue management.
 *
 * This file contains the C-side definitions for the bq_mgr Wayland
 * protocol, including interfaces, requests, and events. These are
 * typically generated by wayland-scanner but are provided here directly.
 */
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface bq_buffer_interface;
extern const struct wl_interface bq_consumer_interface;
extern const struct wl_interface bq_provider_interface;

/**
 * @brief Array of Wayland interface pointers.
 *
 * This array is used by the Wayland marshaling functions to determine the
 * type of arguments in messages (requests and events). Each entry corresponds
 * to an argument type, and a NULL entry usually signifies a basic type
 * (int, uint, string, etc.) or that no interface is associated with that
 * particular argument. The indices are used in the `wl_message` structures.
 *
 * For example, `types + 3` points to `&bq_consumer_interface`, indicating
 * that the argument at that position in a message signature is a new
 * `bq_consumer` object.
 */
static const struct wl_interface *types[] = {
	NULL, /* No interface, typically for basic types or placeholders */
	NULL, /* No interface */
	NULL,
	&bq_consumer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_provider_interface,
	NULL,
	&bq_buffer_interface,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	&bq_buffer_interface,
	NULL,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&bq_buffer_interface,
	&bq_buffer_interface,
	NULL,
	&bq_buffer_interface,
	NULL,
};

/** @brief Requests for the bq_mgr interface. */
static const struct wl_message bq_mgr_requests[] = {
	/**
	 * @brief Create a new buffer queue consumer.
	 * @param id New ID for the bq_consumer object. (Type: new_id, Interface: bq_consumer_interface)
	 * @param name Unique name for the consumer. (Type: string)
	 * @param queue_size Desired size of the buffer queue. (Type: int)
	 * @param width Expected width of buffers. (Type: int)
	 * @param height Expected height of buffers. (Type: int)
	 *
	 * Signature: `nsiii` (new_id, string, int, int, int)
	 * The `n` for `id` uses `types + 3` which is `&bq_consumer_interface`.
	 */
	{ "create_consumer", "nsiii", types + 3 },
	/**
	 * @brief Create a new buffer queue provider.
	 * @param id New ID for the bq_provider object. (Type: new_id, Interface: bq_provider_interface)
	 * @param name Name of the consumer to connect to. (Type: string)
	 *
	 * Signature: `ns` (new_id, string)
	 * The `n` for `id` uses `types + 8` which is `&bq_provider_interface`.
	 */
	{ "create_provider", "ns", types + 8 },
};

/** @brief Definition of the bq_mgr Wayland interface. */
WL_EXPORT const struct wl_interface bq_mgr_interface = {
	"bq_mgr", /**< Interface name */
	1,        /**< Interface version */
	2,        /**< Number of requests */
	bq_mgr_requests, /**< Array of request definitions */
	0, NULL, /**< No events */
};

/** @brief Requests for the bq_consumer interface. */
static const struct wl_message bq_consumer_requests[] = {
	/**
	 * @brief Release a buffer back to the provider.
	 * @param buffer The bq_buffer to release. (Type: object, Interface: bq_buffer_interface)
	 *
	 * Signature: `o` (object)
	 * The `o` for `buffer` uses `types + 10` which is `&bq_buffer_interface`.
	 */
	{ "release_buffer", "o", types + 10 },
};

/** @brief Events for the bq_consumer interface. */
static const struct wl_message bq_consumer_events[] = {
	/** @brief Provider connected. Signature: `` (none) */
	{ "connected", "", types + 0 },
	/** @brief Provider disconnected. Signature: `` (none) */
	{ "disconnected", "", types + 0 },
	/**
	 * @brief Buffer attached by provider.
	 * @param buffer New bq_buffer object. (Type: new_id, Interface: bq_buffer_interface)
	 * @param engine Buffer allocation engine name. (Type: string)
	 * @param width Buffer width. (Type: int)
	 * @param height Buffer height. (Type: int)
	 * @param format Buffer pixel format. (Type: int)
	 * @param flags Buffer usage flags. (Type: uint)
	 *
	 * Signature: `nsiiiu` (new_id, string, int, int, int, uint)
	 * The `n` for `buffer` uses `types + 11` which is `&bq_buffer_interface`.
	 */
	{ "buffer_attached", "nsiiiu", types + 11 },
	/**
	 * @brief Set backend-specific buffer ID and plane info.
	 * @param buffer The bq_buffer object. (Type: object, Interface: bq_buffer_interface)
	 * @param id Backend buffer ID. (Type: int)
	 * @param offset0 Plane 0 offset. (Type: int)
	 * @param stride0 Plane 0 stride. (Type: int)
	 * @param offset1 Plane 1 offset. (Type: int)
	 * @param stride1 Plane 1 stride. (Type: int)
	 * @param offset2 Plane 2 offset. (Type: int)
	 * @param stride2 Plane 2 stride. (Type: int)
	 *
	 * Signature: `oiiiiiii` (object, int, int, int, int, int, int, int)
	 * The `o` for `buffer` uses `types + 17` which is `&bq_buffer_interface`.
	 */
	{ "set_buffer_id", "oiiiiiii", types + 17 },
	/**
	 * @brief Set DMABUF file descriptor and plane info.
	 * @param buffer The bq_buffer object. (Type: object, Interface: bq_buffer_interface)
	 * @param fd File descriptor for the buffer. (Type: fd)
	 * @param offset0 Plane 0 offset. (Type: int)
	 * @param stride0 Plane 0 stride. (Type: int)
	 * @param offset1 Plane 1 offset. (Type: int)
	 * @param stride1 Plane 1 stride. (Type: int)
	 * @param offset2 Plane 2 offset. (Type: int)
	 * @param stride2 Plane 2 stride. (Type: int)
	 *
	 * Signature: `ohiiiiii` (object, fd, int, int, int, int, int, int)
	 * The `o` for `buffer` uses `types + 25` which is `&bq_buffer_interface`.
	 */
	{ "set_buffer_fd", "ohiiiiii", types + 25 },
	/**
	 * @brief Buffer detached by provider.
	 * @param buffer The bq_buffer object that was detached. (Type: object, Interface: bq_buffer_interface)
	 *
	 * Signature: `o` (object)
	 * The `o` for `buffer` uses `types + 33` which is `&bq_buffer_interface`.
	 */
	{ "buffer_detached", "o", types + 33 },
	/**
	 * @brief Buffer enqueued by provider (ready for consumer).
	 * @param buffer The bq_buffer object that was enqueued. (Type: object, Interface: bq_buffer_interface)
	 * @param serial Serial number for the enqueue operation. (Type: uint)
	 *
	 * Signature: `ou` (object, uint)
	 * The `o` for `buffer` uses `types + 34` which is `&bq_buffer_interface`.
	 */
	{ "add_buffer", "ou", types + 34 },
};

/** @brief Definition of the bq_consumer Wayland interface. */
WL_EXPORT const struct wl_interface bq_consumer_interface = {
	"bq_consumer", /**< Interface name */
	1,             /**< Interface version */
	1,             /**< Number of requests */
	bq_consumer_requests, /**< Array of request definitions */
	7,             /**< Number of events */
	bq_consumer_events,   /**< Array of event definitions */
};

/** @brief Requests for the bq_provider interface. */
static const struct wl_message bq_provider_requests[] = {
	/**
	 * @brief Attach a new buffer to the queue.
	 * @param buffer New ID for the bq_buffer object. (Type: new_id, Interface: bq_buffer_interface)
	 * @param engine Buffer allocation engine name. (Type: string)
	 * @param width Buffer width. (Type: int)
	 * @param height Buffer height. (Type: int)
	 * @param format Buffer pixel format. (Type: int)
	 * @param flags Buffer usage flags. (Type: uint)
	 *
	 * Signature: `nsiiiu` (new_id, string, int, int, int, uint)
	 * The `n` for `buffer` uses `types + 36` which is `&bq_buffer_interface`.
	 */
	{ "attach_buffer", "nsiiiu", types + 36 },
	/**
	 * @brief Set backend-specific buffer ID and plane info.
	 * @param buffer The bq_buffer object. (Type: object, Interface: bq_buffer_interface)
	 * @param id Backend buffer ID. (Type: int)
	 * @param offset0 Plane 0 offset. (Type: int)
	 * @param stride0 Plane 0 stride. (Type: int)
	 * @param offset1 Plane 1 offset. (Type: int)
	 * @param stride1 Plane 1 stride. (Type: int)
	 * @param offset2 Plane 2 offset. (Type: int)
	 * @param stride2 Plane 2 stride. (Type: int)
	 *
	 * Signature: `oiiiiiii` (object, int, int, int, int, int, int, int)
	 * The `o` for `buffer` uses `types + 42` which is `&bq_buffer_interface`.
	 */
	{ "set_buffer_id", "oiiiiiii", types + 42 },
	/**
	 * @brief Set DMABUF file descriptor and plane info.
	 * @param buffer The bq_buffer object. (Type: object, Interface: bq_buffer_interface)
	 * @param fd File descriptor for the buffer. (Type: fd)
	 * @param offset0 Plane 0 offset. (Type: int)
	 * @param stride0 Plane 0 stride. (Type: int)
	 * @param offset1 Plane 1 offset. (Type: int)
	 * @param stride1 Plane 1 stride. (Type: int)
	 * @param offset2 Plane 2 offset. (Type: int)
	 * @param stride2 Plane 2 stride. (Type: int)
	 *
	 * Signature: `ohiiiiii` (object, fd, int, int, int, int, int, int)
	 * The `o` for `buffer` uses `types + 50` which is `&bq_buffer_interface`.
	 */
	{ "set_buffer_fd", "ohiiiiii", types + 50 },
	/**
	 * @brief Detach a buffer from the queue.
	 * @param buffer The bq_buffer to detach. (Type: object, Interface: bq_buffer_interface)
	 *
	 * Signature: `o` (object)
	 * The `o` for `buffer` uses `types + 58` which is `&bq_buffer_interface`.
	 */
	{ "detach_buffer", "o", types + 58 },
	/**
	 * @brief Enqueue a buffer for the consumer.
	 * @param buffer The bq_buffer to enqueue. (Type: object, Interface: bq_buffer_interface)
	 * @param serial Serial number for this enqueue operation. (Type: uint)
	 *
	 * Signature: `ou` (object, uint)
	 * The `o` for `buffer` uses `types + 59` which is `&bq_buffer_interface`.
	 */
	{ "enqueue_buffer", "ou", types + 59 },
};

/** @brief Events for the bq_provider interface. */
static const struct wl_message bq_provider_events[] = {
	/**
	 * @brief Provider connected to consumer.
	 * @param queue_size Actual queue size. (Type: int)
	 * @param width Buffer width. (Type: int)
	 * @param height Buffer height. (Type: int)
	 *
	 * Signature: `iii` (int, int, int)
	 */
	{ "connected", "iii", types + 0 },
	/** @brief Provider disconnected from consumer. Signature: `` (none) */
	{ "disconnected", "", types + 0 },
	/**
	 * @brief Buffer released by consumer (ready for provider).
	 * @param buffer The bq_buffer object that was released. (Type: object, Interface: bq_buffer_interface)
	 * @param serial Serial number from the release operation. (Type: uint)
	 *
	 * Signature: `ou` (object, uint)
	 * The `o` for `buffer` uses `types + 61` which is `&bq_buffer_interface`.
	 */
	{ "add_buffer", "ou", types + 61 },
};

/** @brief Definition of the bq_provider Wayland interface. */
WL_EXPORT const struct wl_interface bq_provider_interface = {
	"bq_provider", /**< Interface name */
	1,             /**< Interface version */
	5,             /**< Number of requests */
	bq_provider_requests, /**< Array of request definitions */
	3,             /**< Number of events */
	bq_provider_events,   /**< Array of event definitions */
};

/** @brief Definition of the bq_buffer Wayland interface.
 * This interface has no requests or events itself; it's primarily a marker
 * object passed around in requests and events of other interfaces.
 */
WL_EXPORT const struct wl_interface bq_buffer_interface = {
	"bq_buffer", /**< Interface name */
	1,           /**< Interface version */
	0, NULL,    /**< No requests */
	0, NULL,    /**< No events */
};

