/**
 * @file
 * @brief This file implements the Efl.Io.Writer interface.
 * It primarily serves to include the C source code generated by the
 * Enlightenment Object (Eo) system for this interface.
 */

#define EFL_IO_WRITER_PROTECTED 1 /**< Allows access to protected members from this file. */
#include "config.h" /**< Standard build system configuration header. */
#include "Efl.h" /**< Main EFL header file. */

#include "interfaces/efl_io_writer.eo.c" /**< Includes the generated C source for the Efl.Io.Writer interface. */
