#ifndef _ELM_SYS_NOTIFY_DBUS_EO_H_
#define _ELM_SYS_NOTIFY_DBUS_EO_H_

/**
 * @file
 * @brief These routines are EFL Eolian C an Eo header.
 *
 * This was generated by the Eolian C Bindings tool.
 *
 * DO NOT EDIT THIS FILE OR YOU MAY LOSE YOUR CHANGES.
 *
 * @ingroup Elm_Sys_Notify_Dbus
 */

#ifndef _ELM_SYS_NOTIFY_DBUS_EO_CLASS_TYPE
#define _ELM_SYS_NOTIFY_DBUS_EO_CLASS_TYPE

/**
 * @brief Type definition for the Elm_Sys_Notify_Dbus class.
 * @ingroup Elm_Sys_Notify_Dbus
 */
typedef Eo Elm_Sys_Notify_Dbus;

#endif

#ifndef _ELM_SYS_NOTIFY_DBUS_EO_TYPES
#define _ELM_SYS_NOTIFY_DBUS_EO_TYPES


#endif
/** Elementary system notification DBus class
 *
 * @ingroup Elm_Sys_Notify_Dbus
 */
#define ELM_SYS_NOTIFY_DBUS_CLASS elm_sys_notify_dbus_class_get() /**< @brief Macro to get the Elm_Sys_Notify_Dbus class. @ingroup Elm_Sys_Notify_Dbus */

/**
 * @brief Get the Efl_Class for Elm_Sys_Notify_Dbus.
 * @return The Efl_Class for Elm_Sys_Notify_Dbus.
 * @ingroup Elm_Sys_Notify_Dbus
 */
EWAPI const Efl_Class *elm_sys_notify_dbus_class_get(void) EINA_CONST;

#endif
