/**
 * @file
 * @brief System Notification Manager
 *
 * This file implements the Elm_Sys_Notify module, which provides a
 * unified interface for sending system notifications. It acts as a
 * singleton manager that can interact with various notification
 * server backends, primarily D-Bus based notification services.
 *
 * The manager handles the creation and lifecycle of notification
 * server instances and dispatches notification requests (send, close)
 * to all registered servers. It also defines Ecore events for
 * notification closure and action invocation.
 */

#ifdef HAVE_CONFIG_H
# include "elementary_config.h"
#endif

#include <Elementary.h>

#include "elm_priv.h"

#include "elm_sys_notify_interface_eo.h"
#include "elm_sys_notify_eo.h"
#include "elm_sys_notify_dbus_eo.h"
#include "elm_sys_notify_dbus_eo.legacy.h"

#define MY_CLASS ELM_SYS_NOTIFY_CLASS

#define MY_CLASS_NAME        "Elm_Sys_Notify"
#define MY_CLASS_NAME_LEGACY "elm_sys_notify"

/**
 * @brief Event type for notification closed.
 * @details This event is triggered when a notification is closed.
 * The event info will be the notification ID (unsigned int).
 */
EAPI int ELM_EVENT_SYS_NOTIFY_NOTIFICATION_CLOSED = 0;

/**
 * @brief Event type for action invoked on a notification.
 * @details This event is triggered when an action is invoked on a notification.
 * The event info will be an Elm_Sys_Notify_Action_Invocation struct.
 */
EAPI int ELM_EVENT_SYS_NOTIFY_ACTION_INVOKED      = 0;

/**
 * @brief Function pointer type for getting an Efl_Class.
 * @return A pointer to the Efl_Class, or NULL if not available.
 */
typedef const Efl_Class *(*Class_Get_Func)(void);

/**
 * @brief Singleton instance of the Elm_Sys_Notify manager.
 */
static Elm_Sys_Notify *_singleton = NULL;

/*
 * Registration of notification servers is done UNIQUELY
 * in the two structures below.
 *   1) ALWAYS add a SRV_XXX before __SRV_LAST
 *   2) copy the #if ... #else ... #endif with the appropriate class
 *      getter (generated by Eolian) or NULL when unsupported
 *
 * The rest of the code relies on the Srv enum and _class_getters
 * to register/unregister notification servers.
 */

/**
 * @brief Enumeration of supported notification server types.
 * @details This enum is used to identify and manage different
 *          notification server backends.
 */
typedef enum
{
   SRV_DBUS = 0, /**< D-Bus based notification server. This is the primary and often only type. */
   __SRV_LAST    /**< Sentinel value to mark the end of the enum. Should not be used directly. */
} Srv;

/**
 * @brief Array of function pointers to get the Efl_Class for each server type.
 * @details This array maps Srv enum values to functions that return the
 *          Efl_Class for the corresponding notification server implementation.
 *          If a server type is not compiled in, its entry will be NULL.
 *          Example: _class_getters[SRV_DBUS] would point to elm_sys_notify_dbus_class_get.
 */
static Class_Get_Func _class_getters[__SRV_LAST] =
{
#ifdef ELM_SYS_NOTIFY_DBUS_CLASS
   [SRV_DBUS] = elm_sys_notify_dbus_class_get
#else
   [SRV_DBUS] = NULL
#endif
};


/**
 * @brief Internal data structure for the Elm_Sys_Notify object.
 * @details This structure holds the instances of the notification servers
 *          managed by Elm_Sys_Notify. The `servers` array stores Eo pointers
 *          to the server objects, indexed by the Srv enum.
 *          For example, `sd->servers[SRV_DBUS]` would hold the D-Bus server object.
 */
typedef struct
{
   Eo *servers[__SRV_LAST]; /**< Array of active notification server instances. */
} Elm_Sys_Notify_Data;

/*============================================================================*
 *                  Constructor/Destructor - Singleton setup                  *
 *============================================================================*/

/**
 * @brief Constructor for the Elm_Sys_Notify object.
 * @details This function is called when a new Elm_Sys_Notify object is created.
 *          It ensures that only one instance (singleton) of the manager exists.
 * @param obj The Eolian object being constructed.
 * @param sd The private data for the Elm_Sys_Notify object.
 * @return The constructed Eolian object, or NULL if another instance already exists.
 */
EOLIAN static Efl_Object *
_elm_sys_notify_efl_object_constructor(Eo                  *obj,
                                    Elm_Sys_Notify_Data *sd  EINA_UNUSED)
{
   if (_singleton != NULL)
     {
        ERR("Attempted to create another system notification manager");
        return NULL;
     }

   obj = efl_constructor(efl_super(obj, MY_CLASS));
   _singleton = obj;

   return obj;
}

/**
 * @brief Destructor for the Elm_Sys_Notify object.
 * @details This function is called when the Elm_Sys_Notify object is destroyed.
 *          It resets the singleton instance pointer.
 * @param obj The Eolian object being destructed.
 * @param sd The private data for the Elm_Sys_Notify object.
 */
EOLIAN static void
_elm_sys_notify_efl_object_destructor(Eo                  *obj,
                                   Elm_Sys_Notify_Data *sd  EINA_UNUSED)
{
   efl_destructor(efl_super(obj, MY_CLASS));
   _singleton = NULL;
}


/*============================================================================*
 *                           Notification Interface                           *
 *============================================================================*/

/**
 * @brief Sends a notification through all registered servers.
 * @details Implements the Elm_Sys_Notify_Interface send method. This function
 *          iterates through all active server instances (e.g., D-Bus) and
 *          forwards the send request to each of them.
 *
 * @param obj The Elm_Sys_Notify object (unused, as it's a singleton context).
 * @param sd The private data of the Elm_Sys_Notify object, containing server instances.
 * @param replaces_id ID of the notification to replace, or 0 for a new one.
 * @param icon Path to an icon file or a stock icon name.
 * @param summary A brief summary of the notification.
 * @param body The detailed body text of the notification.
 * @param urgency The urgency level of the notification (e.g., ELM_SYS_NOTIFY_URGENCY_NORMAL).
 * @param timeout The timeout in milliseconds for the notification to be displayed.
 *                A value of -1 means server default, 0 means persist.
 * @param cb Callback function to be invoked with the notification ID once sent.
 * @param cb_data User data to be passed to the callback function.
 */
EOLIAN static void
_elm_sys_notify_elm_sys_notify_interface_send(const Eo *obj EINA_UNUSED,
                                              Elm_Sys_Notify_Data *sd,
                                              unsigned int replaces_id,
                                              const char *icon,
                                              const char *summary,
                                              const char *body,
                                              Elm_Sys_Notify_Urgency urgency,
                                              int timeout,
                                              Elm_Sys_Notify_Send_Cb cb,
                                              const void *cb_data)
{
   Srv i;

   /* Propagate to all registered servers */
   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     if (sd->servers[i])
       elm_obj_sys_notify_interface_send(sd->servers[i], replaces_id, icon, summary, body, urgency, timeout, cb, cb_data);
}

/**
 * @brief Sends a simple notification (icon, summary, body) through all registered servers.
 * @details Implements the Elm_Sys_Notify_Interface simple_send method. This is a
 *          convenience function that sends a notification with default urgency
 *          and timeout. It iterates through all active server instances and
 *          forwards the request.
 *
 * @param obj The Elm_Sys_Notify object (unused).
 * @param sd The private data of the Elm_Sys_Notify object.
 * @param icon Path to an icon file or a stock icon name.
 * @param summary A brief summary of the notification.
 * @param body The detailed body text of the notification.
 */
EOLIAN static void
_elm_sys_notify_elm_sys_notify_interface_simple_send(const Eo *obj EINA_UNUSED,
                                                     Elm_Sys_Notify_Data *sd,
                                                     const char *icon,
                                                     const char *summary,
                                                     const char *body)
{
   Srv i;

   /* Propagate to all registered servers */
   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     if (sd->servers[i])
       elm_obj_sys_notify_interface_simple_send(sd->servers[i], icon, summary, body);
}

/**
 * @brief Closes a notification on all registered servers.
 * @details Implements the Elm_Sys_Notify_Interface close method. This function
 *          iterates through all active server instances and requests each
 *          to close the notification with the given ID.
 *
 * @param obj The Elm_Sys_Notify object (unused).
 * @param sd The private data of the Elm_Sys_Notify object.
 * @param id The ID of the notification to close.
 */
EOLIAN static void
_elm_sys_notify_elm_sys_notify_interface_close(const Eo *obj EINA_UNUSED,
                                               Elm_Sys_Notify_Data *sd,
                                               unsigned int id)
{
   Srv i;

   /* Propagate to all registered servers */
   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     if (sd->servers[i])
       elm_obj_sys_notify_interface_close(sd->servers[i], id);
}


/*============================================================================*
 *                                   Methods                                  *
 *============================================================================*/

/**
 * @brief Sets the active notification servers.
 * @details This function configures which notification server backends are active.
 *          It iterates through all known server types (defined in Srv enum).
 *          If a server type is specified in the `servers` bitmask and not
 *          currently active, it attempts to create an instance of it.
 *          If a server type is not in the `servers` bitmask but is currently
 *          active, its instance is deleted.
 *
 * @param obj The Elm_Sys_Notify object (unused).
 * @param sd The private data of the Elm_Sys_Notify object.
 * @param servers A bitmask of Elm_Sys_Notify_Server flags indicating which
 *                servers to enable. For example, `ELM_SYS_NOTIFY_SERVER_DBUS`.
 * @return EINA_TRUE on success, EINA_FALSE on failure (e.g., unsupported server,
 *         failed to create server instance).
 */
EOLIAN static Eina_Bool
_elm_sys_notify_servers_set(Eo                     *obj  EINA_UNUSED,
                            Elm_Sys_Notify_Data    *sd,
                            Elm_Sys_Notify_Server   servers)
{
   Srv i;
   Class_Get_Func class_get;

   /* Update the notification servers */
   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     {
        if (sd->servers[i])
          {
             /* Delete if server type is not provided */
             if (!(servers & (1 << i)))
               efl_del(sd->servers[i]);
          }
        else
          {
             /* If server is required, create when nonexistant */
             if (servers & (1 << i))
               {
                  class_get = _class_getters[i];
                  if (!class_get)
                    {
                       CRI("Unsupported notification server");
                       return EINA_FALSE;
                    }

                  sd->servers[i] = efl_add(class_get(), NULL);
                  if (EINA_UNLIKELY(!(sd->servers[i])))
                    {
                       CRI("Failed to create notification server");
                       return EINA_FALSE;
                    }
               }
          }
     }

   return EINA_TRUE;
}

/**
 * @brief Gets the currently active notification servers.
 * @details This function returns a bitmask representing all currently
 *          initialized and active notification server backends.
 *
 * @param obj The Elm_Sys_Notify object (unused).
 * @param sd The private data of the Elm_Sys_Notify object.
 * @return A bitmask of Elm_Sys_Notify_Server flags indicating active servers.
 *         For example, if D-Bus server is active, it returns `ELM_SYS_NOTIFY_SERVER_DBUS`.
 */
EOLIAN static Elm_Sys_Notify_Server
_elm_sys_notify_servers_get(const Eo            *obj EINA_UNUSED,
                            Elm_Sys_Notify_Data *sd)
{
   Elm_Sys_Notify_Server servers = ELM_SYS_NOTIFY_SERVER_NONE;
   Srv i;

   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     if (sd->servers[i])
       servers |= (1 << i);

   return servers;
}

/**
 * @brief Gets the singleton instance of the Elm_Sys_Notify manager.
 * @details If the singleton instance does not exist, it is created.
 *          This ensures that there is only one system notification manager.
 * @return A pointer to the Elm_Sys_Notify singleton instance.
 */
EOLIAN static Elm_Sys_Notify *
_elm_sys_notify_singleton_get(void)
{
   if (!_singleton)
     _singleton = efl_add(MY_CLASS, efl_main_loop_get());
   return _singleton;
}

/**
 * @brief Class constructor for Elm_Sys_Notify.
 * @details This function is called once when the Elm_Sys_Notify class is constructed.
 *          It initializes the Ecore event types for notification closed and action invoked.
 * @param klass The Efl_Class being constructed (unused).
 */
EOLIAN static void
_elm_sys_notify_class_constructor(Efl_Class *klass EINA_UNUSED)
{
   ELM_EVENT_SYS_NOTIFY_NOTIFICATION_CLOSED = ecore_event_type_new();
   ELM_EVENT_SYS_NOTIFY_ACTION_INVOKED = ecore_event_type_new();
}

/*============================================================================*
 *                                 Legacy API                                 *
 *============================================================================*/

/**
 * @brief Deinitializes the system notification manager (legacy).
 * @details This function is part of the legacy API. It retrieves the
 *          singleton manager, sets its active servers to NONE (which
 *          effectively deinitializes them), and then deletes the manager.
 *          This is typically called when system notifications are no longer needed.
 */
void
_elm_unneed_sys_notify(void)
{
   Elm_Sys_Notify *manager = elm_obj_sys_notify_singleton_get();
   if (manager)
     {
        elm_obj_sys_notify_servers_set(manager, ELM_SYS_NOTIFY_SERVER_NONE);
        efl_del(manager);
     }
}

/**
 * @brief Initializes the system notification framework (legacy).
 * @details This function is part of the legacy API. It initializes the
 *          system notification manager singleton and attempts to set up
 *          all available notification servers (e.g., D-Bus).
 *          It should be called before sending any notifications if using
 *          the legacy API. If servers are already configured, this function
 *          will report an error.
 *
 * @return EINA_TRUE if initialization was successful and at least one
 *         notification server was set up, EINA_FALSE otherwise.
 * @see elm_sys_notify_servers_set() for more flexible server configuration.
 */
EAPI Eina_Bool
elm_need_sys_notify(void)
{
   Elm_Sys_Notify_Server servers = ELM_SYS_NOTIFY_SERVER_NONE;
   Elm_Sys_Notify *manager;
   Srv i;

   /* In theory, there can be N notification managers, but
    * in the implementation there will be only one: the
    * singleton which is initialized here. */
   manager = elm_obj_sys_notify_singleton_get();
   if (EINA_UNLIKELY(!manager))
     {
        CRI("Failed to get notification manager");
        return EINA_FALSE;
     }

   /* If servers have alread been configured, this is not the right
    * function to be called! */
   if (elm_sys_notify_servers_get(manager) != ELM_SYS_NOTIFY_SERVER_NONE)
     {
        ERR("Notification servers have already been configured. "
            "Use elm_sys_notify_servers_set() instead.");
        return EINA_FALSE;
     }

   /* Register available notification servers */
   for (i = SRV_DBUS; i < __SRV_LAST; ++i)
     if (_class_getters[i])
       servers |= (1 << i);

   /* If no server are available, don't even bother... */
   if (servers == ELM_SYS_NOTIFY_SERVER_NONE)
     return EINA_FALSE;

   return elm_sys_notify_servers_set(manager, servers);
}

EAPI void
elm_sys_notify_send(unsigned int            replaces_id,
                    const char             *icon,
                    const char             *summary,
                    const char             *body,
                    Elm_Sys_Notify_Urgency  urgency,
                    int                     timeout,
                    Elm_Sys_Notify_Send_Cb  cb,
                    const void             *cb_data)
{
   elm_obj_sys_notify_interface_send(_singleton, replaces_id, icon, summary, body, urgency, timeout, cb, cb_data);
}

EAPI void
elm_sys_notify_close(unsigned int id)
{
   elm_obj_sys_notify_interface_close(_singleton, id);
}

#include "elm_sys_notify_eo.c"

