/**
 * @file
 * @brief These routines are EFL Eolian C an Eo implementation.
 *
 * This was generated by the Eolian C Bindings tool.
 *
 * DO NOT EDIT THIS FILE OR YOU MAY LOSE YOUR CHANGES.
 *
 * @ingroup Elm_Sys_Notify_Dbus
 */

/**
 * @internal
 * @brief Constructor for Elm_Sys_Notify_Dbus objects.
 * @param[in] obj The object to construct.
 * @param[in] pd Private data for the object.
 * @return The new object or @c NULL on failure.
 */
Efl_Object *_elm_sys_notify_dbus_efl_object_constructor(Eo *obj, void *pd);


/**
 * @internal
 * @brief Destructor for Elm_Sys_Notify_Dbus objects.
 * @param[in] obj The object to destruct.
 * @param[in] pd Private data for the object.
 */
void _elm_sys_notify_dbus_efl_object_destructor(Eo *obj, void *pd);

/**
 * @internal
 * @brief Implementation of elm_obj_sys_notify_interface_send for Elm_Sys_Notify_Dbus.
 * @param[in] obj The object.
 * @param[in] pd Private data for the object.
 * @param[in] replaces_id The ID of the notification to replace, or 0 for a new notification.
 * @param[in] icon The icon name or path.
 * @param[in] summary The summary text.
 * @param[in] body The body text.
 * @param[in] urgency The urgency level of the notification.
 * @param[in] timeout The timeout in milliseconds, or -1 for default, or 0 for persistent.
 * @param[in] cb The callback function to be called when the notification is closed or the action is invoked.
 * @param[in] cb_data User data to be passed to the callback function.
 */
void _elm_sys_notify_dbus_elm_sys_notify_interface_send(const Eo *obj, void *pd, unsigned int replaces_id, const char *icon, const char *summary, const char *body, Elm_Sys_Notify_Urgency urgency, int timeout, Elm_Sys_Notify_Send_Cb cb, const void *cb_data);

/**
 * @internal
 * @brief Implementation of elm_obj_sys_notify_interface_simple_send for Elm_Sys_Notify_Dbus.
 * @param[in] obj The object.
 * @param[in] pd Private data for the object.
 * @param[in] icon The icon name or path.
 * @param[in] summary The summary text.
 * @param[in] body The body text.
 */
void _elm_sys_notify_dbus_elm_sys_notify_interface_simple_send(const Eo *obj, void *pd, const char *icon, const char *summary, const char *body);

/**
 * @internal
 * @brief Implementation of elm_obj_sys_notify_interface_close for Elm_Sys_Notify_Dbus.
 * @param[in] obj The object.
 * @param[in] pd Private data for the object.
 * @param[in] id The ID of the notification to close.
 */
void _elm_sys_notify_dbus_elm_sys_notify_interface_close(const Eo *obj, void *pd, unsigned int id);

/**
 * @internal
 * @brief Initializes the Elm_Sys_Notify_Dbus class.
 * @param[in] klass The class to initialize.
 * @return @c EINA_TRUE on success, @c EINA_FALSE otherwise.
 */
static Eina_Bool
_elm_sys_notify_dbus_class_initializer(Efl_Class *klass)
{
   const Efl_Object_Ops *opsp = NULL;

   const Efl_Object_Property_Reflection_Ops *ropsp = NULL;

#ifndef ELM_SYS_NOTIFY_DBUS_EXTRA_OPS
#define ELM_SYS_NOTIFY_DBUS_EXTRA_OPS
#endif

   EFL_OPS_DEFINE(ops,
      EFL_OBJECT_OP_FUNC(efl_constructor, _elm_sys_notify_dbus_efl_object_constructor),
      EFL_OBJECT_OP_FUNC(efl_destructor, _elm_sys_notify_dbus_efl_object_destructor),
      EFL_OBJECT_OP_FUNC(elm_obj_sys_notify_interface_send, _elm_sys_notify_dbus_elm_sys_notify_interface_send),
      EFL_OBJECT_OP_FUNC(elm_obj_sys_notify_interface_simple_send, _elm_sys_notify_dbus_elm_sys_notify_interface_simple_send),
      EFL_OBJECT_OP_FUNC(elm_obj_sys_notify_interface_close, _elm_sys_notify_dbus_elm_sys_notify_interface_close),
      ELM_SYS_NOTIFY_DBUS_EXTRA_OPS
   );
   opsp = &ops;

   return efl_class_functions_set(klass, opsp, ropsp);
}

/**
 * @internal
 * @brief Efl_Class_Description for Elm_Sys_Notify_Dbus class.
 */
static const Efl_Class_Description _elm_sys_notify_dbus_class_desc = {
   EO_VERSION,
   "Elm.Sys_Notify.Dbus", /**< @brief The name of the class. */
   EFL_CLASS_TYPE_REGULAR, /**< @brief The type of the class. */
   0,
   _elm_sys_notify_dbus_class_initializer, /**< @brief The class initializer. */
   NULL, /**< @brief The class constructor. */
   NULL /**< @brief The class destructor. */
};

/**
 * @brief Defines the Elm_Sys_Notify_Dbus class.
 *
 * This macro defines the class functions for the Elm_Sys_Notify_Dbus class.
 * It takes the class getter function name, the class description, the parent class,
 * and any implemented interfaces as arguments.
 */
EFL_DEFINE_CLASS(elm_sys_notify_dbus_class_get, &_elm_sys_notify_dbus_class_desc, EFL_OBJECT_CLASS, ELM_SYS_NOTIFY_INTERFACE_INTERFACE, NULL);
